# Generated by Django 5.2.17 on 2026-09-22 01:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('session_type', models.CharField(choices=[('singles', 'Singles'), ('doubles', 'Doubles'), ('open_play', 'Open Play')], max_length=20)),
                ('date_time', models.DateTimeField()),
                ('location_text', models.CharField(max_length=255)),
                ('target_size', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('full', 'Full'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='open', max_length=20)),
                ('waitlist_mode', models.CharField(choices=[('priority_cascade', 'Priority Cascade'), ('fcfs_blast', 'First-Come-First-Serve Blast')], default='priority_cascade', max_length=20)),
                ('participant_visibility', models.CharField(choices=[('visible', 'Visible'), ('hidden', 'Hidden')], default='visible', max_length=10)),
                ('waitlist_offer_window_minutes', models.PositiveIntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date_time'],
            },
        ),
    ]
