# Generated by Django 5.2.17 on 2026-09-22 20:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('tennis_sessions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('in_app_link', 'In-App Link'), ('sms', 'SMS'), ('groupchat_link', 'Group Chat Link')], default='in_app_link', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invited_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_invites', to='categories.category')),
                ('invited_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_invites', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='tennis_sessions.session')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('session', 'invited_user'), name='unique_invite_per_user_per_session'), models.UniqueConstraint(fields=('session', 'invited_category'), name='unique_invite_per_category_per_session'), models.CheckConstraint(condition=models.Q(models.Q(('invited_category__isnull', False), ('invited_user__isnull', True)), models.Q(('invited_category__isnull', True), ('invited_user__isnull', False)), _connector='OR'), name='exactly_one_invite_target')],
            },
        ),
    ]
