# Generated by Django 5.2.17 on 2026-09-26 23:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennis_sessions', '0003_sessionparticipant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='sessionparticipant',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('position__isnull', False), ('status', 'waitlisted')), models.Q(models.Q(('status', 'waitlisted'), _negated=True), ('position__isnull', True)), _connector='OR'), name='waitlist_position_set_iff_waitlisted'),
        ),
    ]
